packages:
  - "core"
  - "flow-editor"
  - "dev-server"
  - "stdlib"
  - "website"
  - "editor"
  - "remote-debugger"
  - "resolver"
  - "runtime"
  - "playground"
  - "vscode-extension"
  - "ui"
  - "!examples/*"
  - "ai"
