name: Build, Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Checkout & Dependencies
        uses: ./.github/workflows/prepare.yaml
      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Lint
        run: yarn run lint

  publish:
    needs: build-test-lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Checkout & Dependencies
        uses: ./.github/workflows/prepare.yml
      - name: Build
        run: yarn run build
      - name: Bump patch version, Publish to NPM (excluding private packages), and Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          for package in $(yarn workspaces list --json | jq -r '.name'); do
            cd packages/$package

            is_private=$(jq '.private' package.json)
            if [[ "$is_private" == "true" ]]; then
              echo "Skipping private package: $package"
              cd ../..
              continue
            fi

            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            npm version patch -m "chore(release): bump version to %s"
            npm publish

            cd ../..
          done

          git add -A
          git commit -m "chore(release): bump package versions"
          git push origin main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
